// Package optionsdb is the embedded knowledge base of mydumper and myloader
// facts per version (design §5): options, table keys, masking functions,
// products, and loader behavior. The data is generated by tools/gen-optionsdb.
package optionsdb

// SchemaVersion is the version of the JSON layout below.
const SchemaVersion = 1

// DB is the whole knowledge base, as stored in data/optionsdb.json. Obtain it
// from Load or Parse: its methods rely on the index Parse builds after
// validating the content.
type DB struct {
	Schema              int       `json:"schema"`
	Versions            []Version `json:"versions"`             // ascending order
	Options             []Option  `json:"options"`              // sorted by (tool, name)
	TableKeys           []Fact    `json:"table_keys"`           // keys of table sections (F8)
	MasqueradeFunctions []Fact    `json:"masquerade_functions"` // masking functions (F10)
	Products            []Fact    `json:"products"`             // lowercase product names (§3.6)

	idx *index // built by Parse; nil for a DB that was not parsed
}

// Version describes one embedded mydumper release.
type Version struct {
	Tag                  string `json:"tag"`                    // e.g. "v0.19.3-3"
	Commit               string `json:"commit"`                 // full commit SHA of the tag
	Date                 string `json:"date,omitempty"`         // GitHub release date, YYYY-MM-DD
	Prerelease           bool   `json:"prerelease"`             // no stable GitHub release (V1)
	IgnoreUnknownOptions bool   `json:"ignore_unknown_options"` // F6
	LoaderFingerprint    string `json:"loader_fingerprint"`     // sha256 of normalized load_config_file + parse_key_file_group
	Preprocessor         bool   `json:"preprocessor"`           // load_config_file runs mydumper's pre-processor (§3.2)
	ImageVerified        bool   `json:"image_verified"`         // cross-check with the official image passed (§5.4)
}

// Range is an inclusive range of version tags. An empty To means "up to the
// newest embedded version".
type Range struct {
	From string `json:"from"`
	To   string `json:"to,omitempty"`
}

// Option is one command-line option of one tool, with its history.
type Option struct {
	Name  string       `json:"name"` // long name, without dashes
	Tool  string       `json:"tool"` // "mydumper" or "myloader"; shared options appear once per tool
	Spans []OptionSpan `json:"spans"`
}

// OptionSpan describes an option over a range of versions in which its
// definition did not change.
type OptionSpan struct {
	Range
	Short string   `json:"short,omitempty"` // one character, or empty
	Arg   string   `json:"arg"`             // none, string, filename, int, int64, double, callback, string_array, filename_array
	Flags []string `json:"flags,omitempty"` // sorted: deprecated, filename, hidden, in_main, no_arg, noalias, optional_arg, reverse
	// Group is the GOptionGroup the option belongs to; empty for the main
	// group. GLib also accepts an option of a non-main group as
	// --<group>-<name>, where <group> may be any prefix of the group name
	// (--conn-port is --port), unless the option is flagged noalias.
	Group            string   `json:"group,omitempty"`
	Condition        string   `json:"condition,omitempty"`          // build condition, e.g. "WITH_SSL" or "WITH_SSL && !LIBMARIADB"
	IsRegex          bool     `json:"is_regex,omitempty"`           // value is a regular expression (MDL406)
	Values           []string `json:"values,omitempty"`             // accepted values when enumerable (callbacks)
	ValuesIgnoreCase bool     `json:"values_ignore_case,omitempty"` // Values are compared ignoring ASCII case
	Description      string   `json:"description,omitempty"`        // always empty: upstream help texts are GPL
	Source           string   `json:"source,omitempty"`             // upstream file:line of the definition in From, for audits
}

// Fact is a named fact that holds over ranges of versions.
type Fact struct {
	Name   string  `json:"name"`
	Prefix bool    `json:"prefix,omitempty"` // matches keys starting with Name (e.g. columns_on_select_replace)
	Spans  []Range `json:"spans"`
}
