package main

import (
	"bytes"
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"regexp"
	"slices"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/tomsihap/mydumper-lint/internal/optionsdb"
)

// imagesFile is tools/gen-optionsdb/images.json, written by -verify-images
// and read by every run to set image_verified (design §5.4). A record only
// counts while the option set it was checked against is unchanged.
type imagesFile struct {
	Comment []string      `json:"comment,omitempty"`
	Images  []imageRecord `json:"images"`
}

type imageRecord struct {
	Tag           string   `json:"tag"`
	Image         string   `json:"image"`
	Digest        string   `json:"digest,omitempty"`   // repository digest of the image that was run
	Mydumper      string   `json:"mydumper,omitempty"` // version the mydumper binary reports
	Myloader      string   `json:"myloader,omitempty"` // version the myloader binary reports
	Library       string   `json:"library,omitempty"`  // client library the binaries report, e.g. "MySQL 8.4.5"
	SSL           bool     `json:"ssl"`                // the binaries report SSL support
	Verified      bool     `json:"verified"`
	OptionsSHA256 string   `json:"options_sha256,omitempty"` // officialOptionsHash of the version when verified
	Problems      []string `json:"problems,omitempty"`
}

var imagesComment = []string{
	"Generated by go run ./tools/gen-optionsdb -verify-images; do not edit.",
	"Each record is the cross-check of one embedded version against the official image",
	"mydumper/mydumper:<tag>: the versions the binaries report, and whether the long and",
	"short option names of --help equal the generated set for the official build.",
}

func loadImages(path string) (*imagesFile, error) {
	var f imagesFile
	b, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		return &f, nil
	}
	if err != nil {
		return nil, err
	}
	dec := json.NewDecoder(bytes.NewReader(b))
	dec.DisallowUnknownFields()
	if err := dec.Decode(&f); err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return &f, nil
}

func (f *imagesFile) record(tag string) (imageRecord, bool) {
	for _, r := range f.Images {
		if r.Tag == tag {
			return r, true
		}
	}
	return imageRecord{}, false
}

// officialOptions returns "tool --name -s" lines for the options of the
// official build that --help lists (hidden options excluded), sorted.
func officialOptions(v *optionsdb.View) []string {
	var out []string
	for _, tool := range tools {
		for _, n := range v.OptionNames(tool) {
			s, _ := v.Option(tool, n)
			if slices.Contains(s.Flags, "hidden") {
				continue
			}
			out = append(out, helpLine(tool, n, s.Short))
		}
	}
	sort.Strings(out)
	return out
}

func helpLine(tool, long, short string) string {
	if short == "" {
		return tool + " --" + long
	}
	return tool + " --" + long + " -" + short
}

func officialOptionsHash(v *optionsdb.View) string {
	sum := sha256.Sum256([]byte(strings.Join(officialOptions(v), "\n")))
	return hex.EncodeToString(sum[:])
}

// runner runs a command and returns its standard output and error.
type runner interface {
	run(ctx context.Context, args ...string) (stdout, stderr string, err error)
}

type execRunner struct{ bin string }

func (r execRunner) run(ctx context.Context, args ...string) (string, string, error) {
	cmd := exec.CommandContext(ctx, r.bin, args...)
	var out, errb bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errb
	err := cmd.Run()
	return out.String(), errb.String(), err
}

var (
	versionRE = regexp.MustCompile(`^(mydumper|myloader) v(\d+\.\d+\.\d+-\d+), built against (\S+) (\S+)( with SSL support)?$`)
	helpRE    = regexp.MustCompile(`^  (?:-(.), )?--([^\s=]+)(?:=\S*)?(?:\s|$)`)
)

// parseHelp returns the "tool --name -s" lines of a --help output.
func parseHelp(tool, out string) []string {
	var lines []string
	for _, l := range strings.Split(out, "\n") {
		m := helpRE.FindStringSubmatch(strings.TrimRight(l, "\r"))
		if m == nil {
			continue
		}
		lines = append(lines, helpLine(tool, m[2], m[1]))
	}
	sort.Strings(lines)
	return lines
}

// diffLines returns "missing from --help: …" and "only in --help: …" lines.
func diffLines(generated, help []string) []string {
	var out []string
	for _, g := range generated {
		if !slices.Contains(help, g) {
			out = append(out, "generated but not in --help: "+g)
		}
	}
	for _, h := range help {
		if !slices.Contains(generated, h) {
			out = append(out, "in --help but not generated: "+h)
		}
	}
	return out
}

// verifyImage cross-checks one version against its official image. db is
// the freshly generated knowledge base.
func verifyImage(ctx context.Context, r runner, db *optionsdb.DB, tag string) imageRecord {
	rec := imageRecord{Tag: tag, Image: "mydumper/mydumper:" + tag}
	problem := func(format string, args ...any) { rec.Problems = append(rec.Problems, fmt.Sprintf(format, args...)) }

	digest, err := imageDigest(ctx, r, rec.Image)
	if err != nil {
		pctx, cancel := context.WithTimeout(ctx, 20*time.Minute)
		_, stderr, perr := r.run(pctx, "pull", "--quiet", rec.Image)
		cancel()
		if perr != nil {
			problem("pull failed: %s", firstLine(stderr, perr))
			return rec
		}
		if digest, err = imageDigest(ctx, r, rec.Image); err != nil {
			problem("inspect failed: %v", err)
			return rec
		}
	}
	rec.Digest = digest

	binaryVersion := ""
	official := true
	for _, tool := range tools {
		out, stderr, err := runTool(ctx, r, rec.Image, tool, "--version")
		line := strings.TrimSpace(out)
		m := versionRE.FindStringSubmatch(line)
		if err != nil || m == nil || m[1] != tool {
			problem("%s --version: unexpected output %q (%s)", tool, line, firstLine(stderr, err))
			return rec
		}
		v := "v" + m[2]
		if tool == "mydumper" {
			rec.Mydumper = v
		} else {
			rec.Myloader = v
		}
		rec.Library = m[3] + " " + m[4]
		rec.SSL = m[5] != ""
		if m[3] != "MySQL" || !rec.SSL {
			official = false
		}
		switch {
		case binaryVersion == "":
			binaryVersion = v
		case binaryVersion != v:
			problem("mydumper and myloader report different versions")
		}
	}
	if !official {
		problem("not the official build (want MySQL client with SSL support): %s, ssl=%v", rec.Library, rec.SSL)
	}
	if binaryVersion != tag {
		problem("image tag %s contains a %s binary", tag, binaryVersion)
	}

	// Compare --help with the generated set of the version the binary
	// reports (the tag itself when the image is right).
	against := tag
	if binaryVersion != tag {
		if _, ok := db.Lookup(binaryVersion); !ok {
			return rec
		}
		against = binaryVersion
	}
	view, err := db.View(against, optionsdb.DefaultBuild)
	if err != nil {
		problem("%v", err)
		return rec
	}
	var help []string
	for _, tool := range tools {
		out, stderr, err := runTool(ctx, r, rec.Image, tool, "--help")
		if err != nil && out == "" {
			problem("%s --help failed: %s", tool, firstLine(stderr, err))
			return rec
		}
		help = append(help, parseHelp(tool, out)...)
	}
	sort.Strings(help)
	mismatches := diffLines(officialOptions(view), help)
	for _, m := range mismatches {
		if against != tag {
			problem("(checked against %s) %s", against, m)
		} else {
			problem("%s", m)
		}
	}
	if against == tag && official && len(rec.Problems) == 0 {
		rec.Verified = true
		rec.OptionsSHA256 = officialOptionsHash(view)
	}
	return rec
}

func runTool(ctx context.Context, r runner, image, tool, arg string) (string, string, error) {
	c, cancel := context.WithTimeout(ctx, 3*time.Minute)
	defer cancel()
	return r.run(c, "run", "--rm", "--entrypoint", tool, image, arg)
}

func imageDigest(ctx context.Context, r runner, image string) (string, error) {
	c, cancel := context.WithTimeout(ctx, time.Minute)
	defer cancel()
	out, stderr, err := r.run(c, "image", "inspect", "--format", "{{json .RepoDigests}}", image)
	if err != nil {
		return "", fmt.Errorf("%s", firstLine(stderr, err))
	}
	var digests []string
	if err := json.Unmarshal([]byte(strings.TrimSpace(out)), &digests); err != nil {
		return "", err
	}
	for _, d := range digests {
		if strings.HasPrefix(d, "mydumper/mydumper@") {
			return strings.TrimPrefix(d, "mydumper/mydumper@"), nil
		}
	}
	if len(digests) > 0 {
		_, d, _ := strings.Cut(digests[0], "@")
		return d, nil
	}
	return "", nil
}

func firstLine(s string, err error) string {
	s = strings.TrimSpace(s)
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	if s == "" && err != nil {
		return err.Error()
	}
	return s
}

// verifyImages checks every version, jobs at a time, and returns the
// records in version order.
func verifyImages(ctx context.Context, r runner, db *optionsdb.DB, jobs int, progress func(imageRecord)) []imageRecord {
	out := make([]imageRecord, len(db.Versions))
	var wg sync.WaitGroup
	sem := make(chan struct{}, max(jobs, 1))
	var mu sync.Mutex
	for i, v := range db.Versions {
		wg.Add(1)
		go func() {
			defer wg.Done()
			sem <- struct{}{}
			defer func() { <-sem }()
			rec := verifyImage(ctx, r, db, v.Tag)
			out[i] = rec
			if progress != nil {
				mu.Lock()
				progress(rec)
				mu.Unlock()
			}
		}()
	}
	wg.Wait()
	return out
}
